### ISSUE TITLE
Takes too long to load

### ISSUE THREAD

**Issue by ClaudiaCF** [ivanvermeyen/laravel-google-drive-demo#19]
i'm using this route in order to get the subelements of an specific folder

```
Route::get('list-folder-contents/{path}', function($path) {
    // The human readable folder name to get the contents of...
    // For simplicity, this folder is assumed to exist in the root directory.
    $folder = $path;

    // Get root directory contents...
    $contents = collect(Storage::cloud()->listContents('/', true));

    // Find the folder you are looking for...
    $dir = $contents->where('type', '=', 'dir')
        ->where('path', '=', $folder);

    if ( ! $dir) {
        return 'No such folder!';
    }

    // Get the files inside the folder...
    return collect(Storage::cloud()->listContents($dir['path'], false));
```

and i need to make it recursive because i want to find the subelements of ANY folder in drive, not just in the root, but it takes too long to load. Any advice?

**Comment by ivanvermeyen** [comment]
Do you get a time-out or does it just take a long time?

When I request all my files and folders recursively it returns 383 items, and it does take about 8 seconds to load. To be honest I'm not quite sure how to make this fast.
I'm not even sure if that's possible. Much depends on how fast the Google Servers process the request, which is beyond our control.

At a quick glance I read about upping the PHP time-out limit.
Or perhaps you could split the request into smaller chunks somehow?

If you can give me some more details I'll research this some more later on.

Perhaps you can also ask this on the Flysystem adapter repo:
https://github.com/nao-pon/flysystem-google-drive/issues
Maybe someone there knows a bit more about this.

**Comment by ClaudiaCF** [comment]
It takes like 10 seconds, which is too long for the project i'm doing. Instead of doing this part:
```
$contents = collect(Storage::cloud()->listContents('/', true));
 $dir = $contents->where('type', '=', 'dir')
        ->where('path', '=', $folder);
```
that i think that is the one that consumes all that time (searching for the folder in all the contents of google drive), isn't there a way to do something like this?
https://developers.google.com/drive/v2/reference/children/list
that given an specific folder id directly gives you all of its content, instead of searching for the folder first

**Comment by ivanvermeyen** [comment]
Oh, of course if you already have the folder ID (path) then you can directly do

```php
return collect(Storage::cloud()->listContents($path, true));
```

Remember you can also gain access to the underlying `Google_Service_Drive` and use more advanced functionality, like in [the example with file permissions](https://github.com/ivanvermeyen/laravel-google-drive-demo/commit/2aa3a23fcdf509f8026f393fcc60f5604f837182).

```php
$service = Storage::cloud()->getAdapter()->getService();
```

Then you can refer to the Google Drive docs for available methods and options.
It does require a fair amount of digging into the guts of Google Drive :)

Note that this uses Google Drive API V3 instead of V2.

Another option I would consider (but it depends on the use case) is to cache the folder structure.
This probably doesn't make sense if you are manipulating files/folders from outside of your app, since it won't be in sync anymore then...

**Comment by ClaudiaCF** [comment]
i can't thank you enough!!! you have no idea how much your proyect has helped me :)
