### ISSUE TITLE
How to change folder id?

### ISSUE THREAD

**Issue by afrasiyabhaider** [ivanvermeyen/laravel-google-drive-demo#68]
I want to access multiple folders but` folderId` is fixed in `filesystem.php`. How can I `change `folder id when I want to access another Google Drive Folder?

**Comment by ivanvermeyen** [comment]
Hi,

The folder ID is being set in the ServiceProvider.
The underlying `GoogleDriveAdapter` requires this.
The ID is indeed fetched from the configuration file.

https://github.com/ivanvermeyen/laravel-google-drive-demo/blob/a545a75b15ac5b16d896a60854c46b5f0bce5300/app/Providers/GoogleDriveServiceProvider.php#L16-L31

One approach could be to use a root folder ID with some subfolders.

Another way is to tweak the code from the ServiceProvider a bit to accept a folder ID instead of using the one from the config. But I don't think you can use Laravel's `extend` functionality then. You'll have to create a custom class or function to do so.

**Comment by afrasiyabhaider** [comment]
I've created a function inside service provider class and then passed a value trough another class ro service provider

--Problem Solved--
