### ISSUE TITLE
Upload directly to drive folder

### ISSUE THREAD

**Issue by felix2056** [ivanvermeyen/laravel-google-drive-demo#74]
I know this issue has already been fixed but I can't seem to get it to work for me as I am new to Laravel.

I already set a folder ID in my env file and i have sub folders inside as well.
Now I want to select any sub folder and upload a file directly to Google disk with custom file name. 

Please can you write a simple code snippet that would work?

**Comment by ivanvermeyen** [comment]
Hello,

[This commit](https://github.com/ivanvermeyen/laravel-google-drive-demo/commit/9176f9fcaff64c07e2d956d5a6d0eaf24ed09b8b) has 2 routes.
One to create a directory and one to create a file in that directory.

The thing to remember is that Google always requires the unique ID's (paths) instead of the human readable name in order to find an existing directory or file. The reason for this is that Google allows duplicate directory/file names.

I hope this helps 👍
