### ISSUE TITLE
Hot to setup credentials that can use in live server only.

### ISSUE THREAD

**Issue by vishal112logistic** [ivanvermeyen/laravel-google-drive-demo#76]
Hello,
I have actually 2 setup, and many local setup.
Because we are multiple developer working, so many time we just copy and paste of env file. So local setup have same credentials and because of this we are facing some issue.

So is there any way that we can give a URL or IP base restriction so only live instance can access such credentials. I think it is possible by API-key but when i check in this credentials this option is not available.

I don't have much idea about google credentials, please help in this.

**Comment by ivanvermeyen** [comment]
Hello,

The normal way that OAuth works is:

- user clicks a button/link
- user gets redirected to Google to grant your app authorization
- user get redirected back to your app
- your app receives the user's refresh token

We are skipping the authorization and redirection part and get the token via the playground, because it's our own Drive that we want to access.

Although you can restrict the redirect URL for when a user clicks the button/link, this has no effect since we are skipping that step. And there doesn't seem to be any other restriction setting for OAuth.
